export const NACOS_CONFIG_TOKEN = Symbol("NACOS_CONFIG_TOKEN");

export const NACOS_CONFIG_METADATA = Symbol('NACOS_CONFIG_METADATA');

export const NACOS_CONFIG_CLIENT_METADATA = Symbol('NACOS_CONFIG_CLIENT_METADATA');
